export const fragments = {
  "first": [
    "Elon Musk",
    "Das Metaverse",
    "Mandy vom Friseursalon \"Haarmony\"",
    "Der alte weiße Mann",
    "Der Tyrannosaurus-Rex",
    "Jan Böhmermann",
    "Ein sehr bekannter Impfstoffhersteller",
    "Billie Eilish",
    "Xavier Naidoo",
    "Der Erfinder des Dyson-Staubsaugers",
    "Wladimir Putin",
    "Die Check24-Familie",
    "Ein rechtsextremer Linksextremist",
    "Kai Pflaume",
    "Eine Influencerin aus Dubai",
    "Die Mafia",
    "Der geheime Sohn von Angela Merkel",
    "Ein Fledermausverkäufer aus Wuhan",
    "Beatrix von Storch",
    "Der Trump-Clan",
    "Peter Wittkamps Gagschreiber",
    "Pia Frey",
    "Der DuMont-Verlag",
    "Der Butler von Micky Beisenherz",
    "Jan Fleischhauer",
    "Die unvermeidliche Lastenrad-Mafia",
    "Die Sekretärin von Ulf Poschardt",
    "Dr. Oetker",
    "Der Spiegel",
    "Die russische Politikerin Sahra Wagenknecht",
    "Der rechte Flügel der taz",
    "Hape Kerkeling in seiner Rolle Angela Merkel",
    "Die Berliner Antifa",
    "Ein betrunkener Blaufußtölpel",
    "eBay Kleinanzeigen",
    "Der Typ, der der Frau in dem Meme etwas ins Ohr brüllt",
    "Der Schauspieler, der uns als Christian Drosten verkauft wurde",
    "Die Zweit-Frau von Friedrich Merz",
    "Der Therapeut von Wolfgang Kubicki",
    "Ein Gecko von Thomas Schmitt",
    "Ein Fan von Gemischtes Hack",
    "Mit Vergnügen",
    "Andreas Scheuer",
    "Die Sparkasse",
    "Ein Zucht-Pferd von Aurel Mertz",
    "Till Reiners",
    "Das heimliche Kind von Heidi Klum und Stefan Raab",
    "Der Algorithmus",
    "Der Postillon",
    "Dein Vater",
    "Dein Partner",
    "Barbara Salesch",
    "Winnetou",
    "Peppa Wutz",
    "Mario Basler",
    "Hubert Aiwanger",
    "Das \"Autoren\"-Duo Welzer und Precht",
    "Die Wagenknecht-Schwarzer-Allianz",
    "Mathias Döpfner"
  ],
  "second": [
    "fälscht seit Jahren Corona-Statistiken,",
    "will den Eiffelturm einschmelzen lassen,",
    "ist der geheime Kopf hinter QAnon,",
    "lebt jeden Tag, als könnte es der Letzte sein,",
    "hat das Corona-Virus in die Welt gesetzt,",
    "hat den Mauerfall befohlen,",
    "möchte Gender-Sternchen ins deutsche Grundgesetz bringen,",
    "soll angeblich den Brexit finanziert haben,",
    "scheint 9/11 verantwortet zu haben,",
    "hat damals die Mon Chéri-Sommerpause angeordnet,",
    "soll die Geburtsurkunde von Barack Obama gefälscht haben,",
    "hat die perfide Chemtrail-Technik entwickelt,",
    "möchte Fleisch in deutschen Supermärkten untersagen,",
    "hat den Körper von Olaf Scholz übernommen,",
    "verheimlicht den genauen Standort des Bernsteinzimmers,",
    "kontrolliert die komplette SPD,",
    "hat die letzte Staffel von Game of Thrones ruiniert,",
    "stellt in einem geheimen Labor Adrenochrom her,",
    "betreut den Telegram-Kanal von Attila Hildmann,",
    "hat den Ersten Weltkrieg ausgelöst,",
    "steckt hinter dem Account von Mario Sixtus",
    "hat sich alle Follower gekauft",
    "kauft heimlich alles bei Amazon",
    "will eine Lastenrad-Pflicht",
    "ist Mitglied bei den Jungen Liberalen geworden",
    "schreibt unter Pseudonym eine Kolumne in der Welt",
    "will ARD und ZDF das Geld streichen",
    "hat noch nie eine Folge des Fernsehgarten verpasst",
    "hat bei Julian Reichelts YouTube-Kanal angeheuert",
    "lügt ohne rot zu werden",
    "verbraucht jeden Tag drei Kilo Hackfleisch",
    "will auf OnlyFans noch mal richtig durchstarten",
    "soll privat zahlreiche Erotik-Videos drehen",
    "findet, die eigenen riechen nicht so schlimm",
    "trägt so Schuhe mit Aussparungen für jeden Zeh",
    "möchte mit Putin verhandeln",
    "ernährt sich nur von Lebensmitteln mit Nutriscore E",
    "will eine Kopfhörer-Plicht",
    "hat in der gesamten Pandemie niemals eine Maske getragen",
    "will ein Insta \"wie früher\"",
    "tritt neuerdings als \"Charles der Dritte\" auf",
    "steckt hinter allen Vorschlägen von Friedrich Merz",
    "will diesen Winter besonders viel Energie verbrauchen",
    "will Nord Stream 2 zu einer Rodelbahn umbauen",
    "fordert ein ganzjähriges Oktoberfest",
    "liked die eigenen Beiträge in Social Media",
    "benutzt keine Zahnseide",
    "möchte ein Tempolimit nur für Veganer durchsetzen",
    "fordert das Generische Femininum",
    "hat die Nordstream-Pipeline gesprengt",
    "hat Twitter gekauft",
    "schmiert die komplette Fifa"
  ],
  "third": [
    "damit der Goldkurs endgültig durch die Decke geht.",
    "einfach nur traurig.",
    "und da muss man sich schon fragen: Cui bono???????",
    "und das ist der Grund, warum Druckertinte so teuer ist.",
    "aber dazu schweigt unsere feine Bundesregierung mal wieder.",
    "und jetzt will es wieder niemand gewusst haben.",
    "und tarnt das alles als Klimapropaganda.",
    "und die Deutschland GmbH ist wieder die große Gewinnerin.",
    "das kann man alles ganz wunderbar auf Wikipedia nachlesen.",
    "alles nur, um die deutsche Spargelernte zu sichern.",
    "!!!!!!!!!1!!!",
    "wodurch die FIFA weiterhin ihr mieses Spielchen treiben kann.",
    "und die da oben verhindern wieder, dass das rauskommt.",
    "ok. Wow.",
    "womit sich natürlich auch erklärt, warum der Euro eingeführt wurde.",
    "und Ken Jebsen hat es die ganze Zeit gewusst.",
    "wodurch die Sprachpolizei weiterhin leichtes Spiel hat.",
    "quod erat demonstrandum.",
    "schön getarnt als Corona \"Schutz\"Maßnahmen.",
    "das stand ja sogar in der Bild-Zeitung.",
    "alles nur, damit die Fischstäbchen-Pizza bleibt!",
    "und das alles nur, um endlich einen blauen Haken zu bekommen.",
    "aber an Bistro Baguettes verbrennt man sich leider immer noch den Gaumen.",
    "das Ziel dahinter ist natürlich, Clubhouse endgültig zu ruinieren",
    "mit welchem langfristigen Ziel ist natürlich kein Geheimnis!",
    "aber das erklärt nicht, warum Nutella mit Butter besser schmeckt.",
    "nur um den Begriff \"ungarische Paprika-Soße\" bekannt zu machen.",
    "ja gut, was will man auch anderes erwarten.",
    "\" plus Märchensteuer!",
    "und damit: Tschüsseldorf!",
    "und deshalb gibt es schon im September Lebkuchen im Supermarkt.",
    "das stand GENAU SO in einem Tweet von El Hotzo.",
    "und dahinter stecken natürlich die Illuminaten!!",
    "natürlich alles mal wieder auf Kosten des Steuerzahlers.",
    "denn nur die Sieger schreiben die Geschichte!",
    "damit Deutschland endlich mit Putin verhandelt!",
    "damit Donald Trump zum zweiten mal Präsident werden kann!!!",
    "\" und das war natürlich der Anfang vom Ende!",
    "damit die Deutschland GmbH endlich abdankt!"
  ]
}