/**
 * Fragmente importiert von https://desinformator.de
 * Ab der Markierung "Beginn eigene Fragmente" eigene Ergänzungen oder Funde aus dem Netz
 * Texte: Pia Frey, Peter Wittkamp
 * 
 */

export const fragments = {
  "first": [
    "Elon Musk",
    "Das Metaverse",
    "Mandy vom Friseursalon \"Haarmony\"",
    "Der alte weiße Mann",
    "Der Tyrannosaurus-Rex",
    "Jan Böhmermann",
    "Billie Eilish",
    "Der Erfinder des Dyson-Staubsaugers",
    "Wladimir Putin",
    "Ein rechtsextremer Linksextremist",
    "Kai Pflaume",
    "Eine Influencerin aus Dubai",
    "Die Mafia",
    "Der geheime Sohn von Angela Merkel",
    "Beatrix von Storch",
    "Der Trump-Clan",
    "Pia Frey",
    "Der DuMont-Verlag",
    "Die unvermeidliche Lastenrad-Mafia",
    "Dr. Oetker",
    "Der Spiegel",
    "Die russische Politikerin Sahra Wagenknecht",
    "Der rechte Flügel der taz",
    "Hape Kerkeling in seiner Rolle Angela Merkel",
    "Die Berliner Antifa",
    "Kleinanzeigen.de",
    "Der Typ, der der Frau in dem Meme etwas ins Ohr brüllt",
    "Der Therapeut von Wolfgang Kubicki",
    "Ein Gecko von Thomas Schmitt",
    "Andreas Scheuer",
    "Die Sparkasse",
    "Das heimliche Kind von Heidi Klum und Stefan Raab",
    "Der Algorithmus",
    "Der Postillon",
    "Barbara Salesch",
    "Peppa Wutz",
    "Die Wagenknecht-Schwarzer-Allianz",
    "Mathias Döpfner",
    /* Beginn eigene Fragmente */
    "Die französische Mafia",
    "Die Zahnfee",
    "Das Sandmännchen",
    "Die angeblich unabhängige WHO",
    "Ein linksradikaler Außerirdischer",
    "Finnley",
    "Der Typ, der immer \"Moin\" sagt",
    "Die Kassiererin von Aldi",
    "Der Paketbote",
    "Die Deutsche Bahn",
    "Die Deutsche Post",
    "Eine Gruppe von angepissten Rentnern",
    "Ein deutsches Imageboard",
    "Der Azubi in der IT-Abteilung",
    "Die russische Trollfabrik",
    "Die Eurofurence Orga",
    "Die Schufa",
    "Der Chaos Computer Club",
  ],
  "second": [
    "will den Eiffelturm einschmelzen lassen,",
    "lebt jeden Tag, als könnte es der Letzte sein,",
    "hat den Mauerfall befohlen,",
    "möchte Gender-Sternchen ins deutsche Grundgesetz bringen,",
    "soll angeblich den Brexit finanziert haben,",
    "scheint 9/11 verantwortet zu haben,",
    "hat damals die Mon Chéri-Sommerpause angeordnet,",
    "soll die Geburtsurkunde von Barack Obama gefälscht haben,",
    "hat die perfide Chemtrail-Technik entwickelt,",
    "möchte Fleisch in deutschen Supermärkten untersagen,",
    "hat den Körper von Olaf Scholz übernommen,",
    "verheimlicht den genauen Standort des Bernsteinzimmers,",
    "kontrolliert die komplette SPD,",
    "hat die letzte Staffel von Game of Thrones ruiniert,",
    "hat den Ersten Weltkrieg ausgelöst,",
    "hat sich alle Follower gekauft",
    "kauft heimlich alles bei Amazon",
    "will eine Lastenrad-Pflicht",
    "ist Mitglied bei den Jungen Liberalen geworden",
    "schreibt unter Pseudonym eine Kolumne in der Welt",
    "will ARD und ZDF das Geld streichen",
    "hat noch nie eine Folge des Fernsehgarten verpasst",
    "hat bei Julian Reichelts YouTube-Kanal angeheuert",
    "lügt ohne rot zu werden",
    "verbraucht jeden Tag drei Kilo Hackfleisch",
    "will auf OnlyFans noch mal richtig durchstarten",
    "soll privat zahlreiche Erotik-Videos drehen",
    "findet, die eigenen riechen nicht so schlimm",
    "trägt so Schuhe mit Aussparungen für jeden Zeh",
    "möchte mit Putin verhandeln",
    "ernährt sich nur von Lebensmitteln mit Nutriscore E",
    "will eine Kopfhörer-Plicht",
    "will ein Insta \"wie früher\"",
    "tritt neuerdings als \"Charles der Dritte\" auf",
    "steckt hinter allen Vorschlägen von Friedrich Merz",
    "will diesen Winter besonders viel Energie verbrauchen",
    "fordert ein ganzjähriges Oktoberfest",
    "liked die eigenen Beiträge in Social Media",
    "benutzt keine Zahnseide",
    "möchte ein Tempolimit nur für Veganer durchsetzen",
    "fordert das Generische Femininum",
    "hat die Nordstream-Pipeline gesprengt",
    "hat Twitter gekauft",
    "schmiert die komplette FIFA",
    /* Beginn eigene Fragmente */
    "ist mit einem Fake-Profil auf Tinder",
    "kontrolliert die Grünen",
    "will Nutella mit Butter verbieten",
    "hat die Seitenbacher-Werbung erfunden",
    "ist mit den Geissens befreundet",
    "instrumentalisiert das Bündnis Sahra Wagenknecht",
    "macht regelmäßig die Eismaschine bei McDonalds kaputt",
    "hat SB-Kassen in Supermärkten eingeführt",
    "hat Scan&Go bei IKEA eingeführt",
    "wird vom DuMont-Verlag verklagt",
    "baut heimlich Gras an",
    "betreibt eine Botfarm für Social Media",
    "betrügt bei Monopoly",
    "leitet absichtlich Pakete falsch weiter",
    "baut das deutsche Schienennetz um",
    "hat die Bielefeld-Verschwörung losgetreten",
    "hat die Mondlandung inszeniert",
    "behauptet, dass Vögel nicht echt sind",
    "hat das OVH Rechenzentrum in Brand gesteckt",
  ],
  "third": [
    "damit der Goldkurs endgültig durch die Decke geht.",
    "einfach nur traurig.",
    "und das ist der Grund, warum Druckertinte so teuer ist.",
    "aber dazu schweigt unsere feine Bundesregierung mal wieder.",
    "und jetzt will es wieder niemand gewusst haben.",
    "und tarnt das alles als Klimapropaganda.",
    "und die Deutschland GmbH ist wieder die große Gewinnerin.",
    "das kann man alles ganz wunderbar auf Wikipedia nachlesen.",
    "alles nur, um die deutsche Spargelernte zu sichern.",
    "!!!!!!!!!1!!!",
    "wodurch die FIFA weiterhin ihr mieses Spielchen treiben kann.",
    "und die da oben verhindern wieder, dass das rauskommt.",
    "ok. Wow.",
    "womit sich natürlich auch erklärt, warum der Euro eingeführt wurde.",
    "wodurch die Sprachpolizei weiterhin leichtes Spiel hat.",
    "quod erat demonstrandum.",
    "das stand ja sogar in der Bild-Zeitung.",
    "alles nur, damit die Fischstäbchen-Pizza bleibt!",
    "und das alles nur, um endlich einen blauen Haken zu bekommen.",
    "aber an Bistro Baguettes verbrennt man sich leider immer noch den Gaumen.",
    "mit welchem langfristigen Ziel ist natürlich kein Geheimnis!",
    "aber das erklärt nicht, warum Nutella mit Butter besser schmeckt.",
    "nur um den Begriff \"ungarische Paprika-Soße\" bekannt zu machen.",
    "ja gut, was will man auch anderes erwarten.",
    "...plus Märchensteuer!",
    "und damit: Tschüsseldorf!",
    "und deshalb gibt es schon im September Lebkuchen im Supermarkt.",
    "das stand GENAU SO in einem Tweet von El Hotzo.",
    "und dahinter stecken natürlich die Illuminaten!!",
    "natürlich alles mal wieder auf Kosten des Steuerzahlers.",
    "denn nur die Sieger schreiben die Geschichte!",
    "damit Deutschland endlich mit Putin verhandelt!",
    "und das war natürlich der Anfang vom Ende!",
    "damit die Deutschland GmbH endlich abdankt!",
    /* Beginn eigene Fragmente */
    "wenn das der Führer mitbekommen hätte",
    "da muss man sich nur mal reinlesen und irgendwann macht's Klick!",
    "und Günther Jauch steckt da auch noch irgendwie mit drin.",
    "aber Günter Wallraff dreht schon die neue Reportage.",
    "aber die große Frage ist: Was hat Bibi Blocksberg damit zu tun?",
    "und darum klebt jetzt auch überall Tesafilm.",
    "was das Gaffa-Verbot im CCH erklärt.",
    "und das hat die LIDL-Plus-App ganz weit nach oben gebracht!",
    "...in Minecraft!",
    "und das ist auch der Grund, warum die Bahn immer Verspätung hat.",
    "weswegen dein Paket jetzt in der Postfiliale liegt.",
    "da fängt der Aluhut an zu glühen!",
    "und deshalb gibt es jetzt auch die 5G-Strahlen.",
    "und das lässt Bitcoin schon wieder abstürzen.",
    "und das katapultiert Bitcoin schon wieder zum Mond.",
    "was das Finanzamt natürlich nicht gerne hört.",
    "aber was sagt der Verifox dazu?",
  ]
}